import { FETCH_ALL,FETCHED_ALL,FETCH_BY_ID,FETCHED_BY_ID,CAPTURE_ID,CAPTURE_SELECT } from "./ActionConstants"
const FETCH_ALL_ACTION=(selectTo) =>({type:FETCH_ALL,selectTo})
const FETCHED_ALL_DATA_ACTION =(data)=>({type:FETCHED_ALL,data})
const FETCH_BY_ID_ACTION=(todoId,selectTo)=>({type:FETCH_BY_ID,todoId,selectTo})
const FETCHED_BY_ID_ACTION =(data)=>({type:FETCHED_BY_ID,data})
const CAPTURE_ID_ACTION=(todoId)=>({type:CAPTURE_ID,todoId})
const CAPTURE_SELECT_ACTION=(select)=>({type:CAPTURE_SELECT,select})

export {FETCH_ALL_ACTION,FETCHED_ALL_DATA_ACTION,FETCH_BY_ID_ACTION,FETCHED_BY_ID_ACTION,
    CAPTURE_ID_ACTION,CAPTURE_SELECT_ACTION}