const FETCH_ALL='FETCH_ALL'
const FETCHED_ALL="FETCHED_ALL"
const FETCH_BY_ID="FETCH_BY_ID"
const FETCHED_BY_ID="FETCHED_BY_ID"
const CAPTURE_ID='CAPTURE_ID'
const CAPTURE_SELECT="CAPTURE_SELECT"

export{FETCHED_ALL,FETCH_ALL,FETCH_BY_ID,FETCHED_BY_ID,CAPTURE_ID,CAPTURE_SELECT}